# 服务器设置
server:
  # 服务http端口
  port: 9500
  # tomcat配置
  tomcat:
    # 设置字符编码
    uri-encoding: UTF-8
    # 最大连接数
    max-connections: 5000
    # 最小线程数
    min-spare-threads: 50
    # 最大线程数
    max-threads: 800
    # 队列长度
    accept-count: 1000
    # 服务器连接建立超时时间
    connection-timeout: 10000
# 配置日志输出级别
logging:
  # 指定logback配置文件的位置 
  config: ${spring.profiles.path}/logback-spring.xml
  # 文件日志要输出的路径
  path: E:/logs/springboot_server
  # 日志的输出级别
  level:
    root: info
