# 服务器设置
server:
  # 服务http端口
  port: 8080
  # tomcat配置
  tomcat:
    # 设置字符编码
    uri-encoding: UTF-8
    # 最大连接数
    max-connections: 5000
    # 最小线程数
    min-spare-threads: 50
    # 最大线程数
    max-threads: 800
    # 队列长度
    accept-count: 1000
    # 服务器连接建立超时时间
    connection-timeout: 10000
# 配置jwt
jwt:
  # token需要放的头部属性名称
  header: Authorization
  # 生成token的秘钥
  secret: aHR0cHM6Ly9teS5vc2NoaW5hLm5ldC91LzM2ODE4Njg=
  # token过期时间
  expire: 7200
  # token前缀
  tokenPrefix: Bearer
  # 平台分的调用平台的用户名和密码（实体集合）
  userlist:
    - appId: YiBaoTong
      passwor: 123456
    - appId: ZhiKe
      password: 123456
# 配置日志输出级别
logging:
  # 指定logback配置文件的位置 
  config: classpath:logback-spring.xml
  # 文件日志要输出的路径
  path: E:/logs/springboot_server
  # 日志的输出级别
  level:
    root: info
# 拦截器路径拦截或者不拦截配置
interceptorconfig:
  path:
    #该路径下任何类型请求均拦截
    include:
      - /api/v1/token/api_token
    #该路径下任何请求均放行
    exclude:
      - /api/v1/yibaotong/save