# 服务器设置
server:
  # 服务http端口
  port: 8080
  # 设置请求头的数据大小
  max-http-header-size: 404857
  # tomcat配置
  tomcat:
    # 设置字符编码
    uri-encoding: UTF-8
    # 最大连接数
    max-connections: 5000
    # 最小线程数
    min-spare-threads: 50
    # 最大线程数
    max-threads: 800
    # 队列长度
    accept-count: 1000
    # 服务器连接建立超时时间
    connection-timeout: 10000
    # 请求参数长度
    max-http-post-size: 30MB
# redis配置
spring:
  # 配置缓存（redis作为缓存）
  cache:
    # 缓存的类型
    type: redis    
  redis:
    # 数据库索引 Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    # 对于单机版的Redis，可以使用此参数指定(数据库index),操作使用哪一个数据库
    # Redis支持多个数据库(默认是16个，可通过配置文件来修改数据库数量)，并且每个数据库的数据是隔离的，不能共享，并且基于单机redis才有
    # 如果是集群就没有数据库的概念，集群只有一个db0数据库
    database: 1
    # redis服务地址
    host: 127.0.0.1
    # 端口号
    port: 6379
    # 连接密码，默认为空
    password: 123456
    # 连接超时时间 单位 ms（毫秒） ，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    timeout: 3000ms
    # lettuce连接池配置
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认值为 8
        max-active: 200
        # 连接池中的最大空闲连接 默认值 8
        max-idle: 200
        # 连接池中的最小空闲连接 默认值 0
        min-idle: 50
        # 连接池最大阻塞等待时间，单位毫秒（使用负值表示没有限制）默认 -1 需要指明单位
        max-wait: -1ms       
# 配置jwt
jwt:
  # token需要放的头部属性名称
  header: Authorization
  # 生成token的秘钥
  secret: aHR0cHM6Ly9teS5vc2NoaW5hLm5ldC91LzM2ODE4Njg=
  # token过期时间(单位：秒)
  expire: 600
  # token前缀
  tokenPrefix: Bearer
  # 签发者
  issuer: sleb
  # 平台分的调用平台的用户名和密码（实体集合）
  userlist:
    - appId: YiBaoTong
      password: 123456
    - appId: ZhiKe
      password: 123456
# 配置日志输出级别
logging:
  # 指定logback配置文件的位置 
  config: classpath:logback-spring.xml
  # 文件日志要输出的路径
  path: C:/logs/springboot_server
  # 日志的输出级别
  level:
    root: info
# 拦截器路径拦截或者不拦截配置
interceptorconfig:
  path:
    #该路径下任何类型请求均拦截
    include:
      - /**
    #该路径下任何请求均放行
    exclude:
      - /api/v1/token/api_token
      - /static/**  #静态资源放行
      - /templates/**  #动态页面放行